use bytestring args to .strip() on vault pass script out
password script output is a bytestring, and the trying to
.strip('some_text') fails with:

TypeError: a bytes-like object is required, not 'str'